### PR TITLE
Ported to 1.19.3

### PR DESCRIPTION
**Pull request by Ayutac**
Tested, seems to work fine.

### CODE REVIEW

**Comment by maxvar** [comment]
you can also upgrade LOOM to 1.0-SNAPHOT

**Comment by lospejos** [comment]
AFAIK Loom could be upgraded even up to 1.1-SNAPSHOT

**Comment by bigenergy** [comment]
https://www.curseforge.com/minecraft/mc-mods/inmis-renewed

**Comment by Globox1997** [comment]
Appreciate the PR but 1.19.3 won't be supported.

**Pull request closed without merging**
